project_id = "ghdvajkciypqapkcbtfx"

[functions.create-checkout]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false
