project_id = "ghdvajkciypqapkcbtfx"

[functions.create-checkout]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.change-plan]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-purchase-receipt]
verify_jwt = false

[functions.send-plan-change-email]
verify_jwt = false

[functions.send-payment-failed-email]
verify_jwt = false
